server.port=8080
spring.application.name=api-gateway

service.user.url=${USER_SERVICE_URL:http://localhost:8081}
service.book.url=${BOOK_SERVICE_URL:http://localhost:8082}
service.borrow.url=${BORROW_SERVICE_URL:http://localhost:8083}
